// # QrScanner = require 'qr-scanner.min.js'
// import QrScanner from '/qr-scanner.min.js'; // if using plain es6 import
import QrScanner from 'qr-scanner'; // if installed via package and bundling with a module bundler like webpack or rollup

QrScanner.WORKER_PATH = 'qr-scanner-worker.min.js';


if (Meteor.isClient) {
  Router.route('/scanner', (function() {
    return this.render('scanner');
  }), {
    name: 'scanner'
  });
  Template.scanner.onCreated(function() {});
  Template.scanner.onRendered(function() {
    const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result));
      
    return console.log(QrScanner);
  });
  Template.scanner.events({
    'click .start': function() {
      console.log(qrScanner);
      qrScanner.start();
    },
    'click .stop': function() {
      qrScanner.stop();
    },
    'click .check': function() {
      qrScanner.hasCamera();
    }
  });
}

// ---
// generated by coffee-script 1.9.2